version: '3'

services:

  jupyter:
    image: redisjupyter/jupyter:tzaffi-0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://cache
    links:
      - redis
    depends_on:
      - redis
      
  redis:
    image: redis:4.0.6-alpine
    volumes:
      - redisdata:/data

volumes:
  jupyterdata:
  redisdata:
